In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv ("kc_final.csv", sep=',', encoding='UTF-8')



print(df)

       Unnamed: 0          id        date     price  bedrooms  bathrooms  \
0               0  7129300520  2014-10-13  221900.0         3       1.00
1               1  6414100192  2014-12-09  538000.0         3       2.25
2               2  5631500400  2015-02-25  180000.0         2       1.00
3               3  2487200875  2014-12-09  604000.0         4       3.00
4               4  1954400510  2015-02-18  510000.0         3       2.00
...           ...         ...         ...       ...       ...        ...
21608       21608   263000018  2014-05-21  360000.0         3       2.50
21609       21609  6600060120  2015-02-23  400000.0         4       2.50
21610       21610  1523300141  2014-06-23  402101.0         2       0.75
21611       21611   291310100  2015-01-16  400000.0         3       2.50
21612       21612  1523300157  2014-10-15  325000.0         2       0.75

       sqft_living  sqft_lot  floors  waterfront  ...  grade  sqft_above  \
0             1180      5650     1.0           0  ...      7        1180
1             2570      7242     2.0           0  ...      7        2170
2              770     10000     1.0           0  ...      6         770
3             1960      5000     1.0           0  ...      7        1050
4             1680      8080     1.0           0  ...      8        1680
...            ...       ...     ...         ...  ...    ...         ...
21608         1530      1131     3.0           0  ...      8        1530
21609         2310      5813     2.0           0  ...      8        2310
21610         1020      1350     2.0           0  ...      7        1020
21611         1600      2388     2.0           0  ...      8        1600
21612         1020      1076     2.0           0  ...      7        1020

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0                  0      1955             0    98178  47.5112 -122.257
1                400      1951          1991    98125  47.7210 -122.319
2                  0      1933             0    98028  47.7379 -122.233
3                910      1965             0    98136  47.5208 -122.393
4                  0      1987             0    98074  47.6168 -122.045
...              ...       ...           ...      ...      ...      ...
21608              0      2009             0    98103  47.6993 -122.346
21609              0      2014             0    98146  47.5107 -122.362
21610              0      2009             0    98144  47.5944 -122.299
21611              0      2004             0    98027  47.5345 -122.069
21612              0      2008             0    98144  47.5941 -122.299

       sqft_living15  sqft_lot15
0               1340        5650
1               1690        7639
2               2720        8062
3               1360        5000
4               1800        7503
...              ...         ...
21608           1530        1509
21609           1830        7200
21610           1020        2007
21611           1410        1287
21612           1020        1357

[21613 rows x 22 columns]